"""add_completed_at_to_timeblocks

Revision ID: 55a08251be90
Revises: 6340ff9496b4
Create Date: 2026-03-08 14:05:05.579781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a08251be90'
down_revision: Union[str, Sequence[str], None] = '6340ff9496b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_blocks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_blocks', 'completed_at')
    # ### end Alembic commands ###
