"""fix habit_log date type and unique constraint

Revision ID: 6340ff9496b4
Revises: d8490d89a0fb
Create Date: 2026-03-08 08:19:14.089244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6340ff9496b4'
down_revision: Union[str, Sequence[str], None] = 'd8490d89a0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit_logs', 'date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using="date::date")
    op.create_unique_constraint('uq_habit_log_habit_date', 'habit_logs', ['habit_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_habit_log_habit_date', 'habit_logs', type_='unique')
    op.alter_column('habit_logs', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
