"""add_source_type_to_time_blocks

Revision ID: afb695ee4279
Revises: 4b9ab60b09fd
Create Date: 2026-03-09 16:00:29.529316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb695ee4279'
down_revision: Union[str, Sequence[str], None] = '4b9ab60b09fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_blocks', sa.Column('source_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_blocks', 'source_type')
    # ### end Alembic commands ###
