"""add_index_routines_user_id

Revision ID: e92b483e525e
Revises: 776ddbe88bda
Create Date: 2026-03-09 16:17:03.325347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92b483e525e'
down_revision: Union[str, Sequence[str], None] = '776ddbe88bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    # ### end Alembic commands ###
